# Generated by Django 4.0.3 on 2022-03-12 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result_store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fever', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('shortness_of_breath', models.BooleanField(default=False)),
                ('head_ache', models.BooleanField(default=False)),
                ('age_60_and_above', models.BooleanField(default=False)),
                ('corona_result', models.BooleanField(null=True)),
            ],
        ),
    ]
